apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tilleggsstonader-alerts
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  groups:
    - name: alerts
      rules:
        - alert: Feilede iverksettinger
          expr: max(andel_tilkjent_ytelse_iverksetting_status{status="FEILET"}) > 0
          for: 10m
          annotations:
            consequence: Vi har mottatt FEILET-status fra hel-ved ved iverksetting
            action: "Sjekk logger for å finne iverksetting-id som har feilet og kontakt hel-ved"
          labels:
            namespace: tilleggsstonader
            severity: critical

        - alert: Iverksettinger uten OK-status
          expr: max(andel_tilkjent_ytelse_iverksetting_status{status="IKKE_MOTTATT_OK_STATUS"}) > 0
          annotations:
            consequence: Iverksettinger uten mottatt OK-status fra hel-ved
            action: "Sjekk logger for å finne iverksetting-id ikke har mottatt OK-status og kontakt hel-ved"
          labels:
            namespace: tilleggsstonader
            severity: critical

        - alert: Error-logg alert
          expr: sum(increase(logback_events_total{app=~"tilleggsstonader-.*",level=~"error"}[5m])) > 0
          annotations:
            consequence: Det har blitt logget error i tilleggsstonader
            action: "Sjekk <https://logs.az.nav.no/app/data-explorer/discover?security_tenant=navlogs#/view/08ba2c80-c55b-11f0-a352-7f33fcf8355a?_g=%28filters%3A%21%28%29%2CrefreshInterval%3A%28pause%3A%21t%2Cvalue%3A0%29%2Ctime%3A%28from%3Anow%2Fd%2Cto%3Anow%2Fd%29%29|logs> eller <https://cloudlogging.app.goo.gl/SLoLZHpa2Ywu3KAa8|secure logs>"
          labels:
            namespace: tilleggsstonader
            severity: critical

        - alert: Feilet task i Tilleggsstønader
          expr: max(prosessering_tasks_feilet{team="tilleggsstonader"}) > 0
          annotations:
            consequence: "{{ $value }} prosesseringstasks har feilet"
            action: "Sjekk prosessering: https://tilleggsstonader-prosessering.intern.nav.no/"
          labels:
            namespace: tilleggsstonader
            severity: critical

        - alert: Behandlinger uten oppgave i TS-sak
          expr: max(behandlinger_uten_oppgave{team="tilleggsstonader"}) > 0
          annotations:
            consequence: "{{ $value }} åpne behandlinger har ingen gyldig oppgave tilknyttet seg, vil ikke bli synlig i oppgavebenken"
            action: "Hvis oppgave har blitt ferdigstilt manuelt eller flyttet til en ukjent enhet kan det opprettes ny oppgave gjennom TS-sak sin swagger."
          labels:
            namespace: tilleggsstonader
            severity: critical

        - alert: Iverksetting har gått over rest
          expr: sum(increase(iverksettinger_til_helved_total{namespace="tilleggsstonader", type="rest"}[1h])) > 0
          annotations:
            consequence: "Forventer ikke iverksettinger over rest lenger"
            action: "Sjekk ut hvilken sak og hvorfor den har blitt utbetalt over rest"
          labels:
            namespace: tilleggsstonader
            severity: critical
