name: "attest-sign"
description: "Attester og signer SBOM"
inputs:
  digest:
    description: "Docker image digest"
    required: true
runs:
  using: composite
  steps:
    - name: NAIS login
      uses: nais/login@v0
      id: login
      with:
        team: tilleggstonader
    - id: setup
      shell: bash
      run: |
        repo_name="${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}"
        repo_name="$(tr "[:upper:]" "[:lower:]" <<< "$repo_name")"
        echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT
    - name: "Attester og signer SBOM"
      id: attest-sign
      uses: nais/attest-sign@v1
      with:
        image_ref: ${{ steps.login.outputs.registry }}/${{ steps.setup.outputs.REPO_NAME }}@${{ inputs.digest }}
