name: "attest-sign"
description: "Attester og signer SBOM"
inputs:
  digest:
    description: "Docker image digest"
    required: true
runs:
  using: composite
  steps:
    - name: "Nais login"
      uses: nais/login@c88ada9ce583928e1c84d2fd5c45cfacdd18d5de # v0
      id: login
      with:
        team: tilleggsstonader

    - name: "Hent ut navn på repo"
      id: setup
      shell: bash
      run: |
        repo_name="${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}"
        repo_name="$(tr "[:upper:]" "[:lower:]" <<< "$repo_name")"
        echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT

    - name: "Attester og signer SBOM"
      id: attest-sign
      uses: nais/attest-sign@d8ec1989b5d1eb59809b050149713002f3de8e2d # v2
      with:
        image_ref: ${{ steps.login.outputs.registry }}/${{ steps.setup.outputs.REPO_NAME }}@${{ inputs.digest }}
