name: Bygg og deploy til prod og dev

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy.yml@main
    secrets: inherit
    with:
      cluster: 'dev-gcp'
      manifest: '.nais/dev.yml'
