name: Bygg og deploy til prod og dev

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    name: "Bygger app og deployer til prod og dev"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy-prod-and-dev.yml@main
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
    with:
      prod-cluster: 'prod-gcp'
      prod-manifest: '.nais/prod.yml'
      dev-cluster: 'dev-gcp'
      dev-manifest: '.nais/dev.yml'
