name: Manuell deploy til dev

on:
  workflow_dispatch:
    inputs:
      skip-checks:
        description: "Hopp over testing og linting"
        type: boolean
        required: false
        default: false

jobs:
  build_and_deploy:
    name: "Bygger app og deployer til dev"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read   # Kan fjernes hvis du kaller jobben fra et offentlig repo
      id-token: write  # Kreves av nais/login
    with:
      cluster: 'dev-gcp'
      manifest: '.nais/dev.yml'
      skip-checks: ${{ github.event.inputs.skip-checks == true }}
