name: Manuell deploy til dev

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: "Bygger app og deployer til dev"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy.yml@main
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
    with:
      cluster: 'dev-gcp'
      manifest: '.nais/dev.yml'
