name: Manuell deploy til dev

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-deploy-prod-and-dev.yml@main
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
    with:
      prod-cluster: 'prod-gcp'
      prod-manifest: '.nais/prod.yml'
      dev-cluster: 'dev-gcp'
      dev-manifest: '.nais/dev.yml'
