name: Manuell deploy til dev

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    uses: navikt/tilleggsstonader/.github/workflows/java/build-and-deploy-prod-and-dev.yml@main
    secrets: inherit
    with:
      prod-cluster: 'prod-gcp'
      prod_manifest: '.nais/prod.yml'
      dev-cluster: 'dev-gcp'
      dev_manifest: '.nais/dev.yml'
