name: Deploy BigQuery Resources

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: "\
            .nais/metabase-views/avslag-arsaker.yml,\
            .nais/metabase-views/sett-pa-vent-arsaker.yml,\
            .nais/metabase-views/sett-pa-vent-varighet.yml,\
            .nais/metabase-views/totrinn-arsaker-til-retur.yml,\
            .nais/metabase-views/vedtak-offentlig-transport.yml,\
            .nais/metabase-views/vedtak-privat-bil.yml,\
            .nais/metabase-views/saksbehandling.yml"
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true
