name: Bygg og deploy app til angitt miljø

# ------------------------------------------------------------
# Denne workflowen bygger en Java-applikasjon, pusher docker-image til GAR og
# deployerer det hele til et spesifisert cluster, ut i fra et gitt tilhørende Nais-manifest.
#
# ** Denne jobben hopper over testing og linting **
#
# Det er påkrevd at kallende GitHub Actions-jobb setter følgende rettigheter:
#
# permissions:
#  contents: write         # Kreves av nais/login
#  id-token: write         # Kreves for å skrive sårbarhetsanalyse-rapport
#  security-events: write  # Kreves for å pushe resultat av sårbarhetsanalyse til Github Security

# ------------------------------------------------------------

on:
  workflow_call:
    inputs:
      cluster:
        description: 'Cluster det skal deployes til'
        required: true
        type: string
      manifest:
        description: 'Sti til Nais-manifestet'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: "Bygg, test og push docker-image"
    runs-on: ubuntu-latest
    timeout-minutes: 8
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
      digest: ${{ steps.docker-push.outputs.digest }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: "Kjør tester"
        run: ./gradlew test -PskipLint

      - name: "Bygg applikasjonen"
        run: ./gradlew bootJar -PskipLint

      - name: "Push image til GAR"
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # v0
        id: docker-push
        with:
          team: tilleggsstonader
          salsa: false

  salsa:
    name: "Attester og signer SBOM"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: navikt/tilleggsstonader/.github/actions/attest-sign@3d7a1dfe34c2ee71819088812888d7924a5b356c # main
        with:
          digest: ${{ needs.build.outputs.digest }}

  deploy:
    name: "Deploy til ${{ inputs.cluster }}"
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.manifest }}
          IMAGE: ${{ needs.build.outputs.image }}
