name: Send inn avhengighetsgraf til GitHub Security

# ------------------------------------------------------------
# Denne workflowen genererer og sender inn en avhengighetsgraf til GitHiub Security,
# slik at dependabot kan danne et fullstendig bilde av avhengighetene i prosjektet.
#
# Det er påkrevd at kallende GitHub Actions-jobb setter følgende rettigheter:
#
# permissions:
#   contents: "write"   # Kreves av Dependency Submission API-et
# ------------------------------------------------------------

on:
  workflow_call:
    inputs: { }

jobs:
  dependencies:
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Sett opp Gradle til å generere og sende inn avhengighetsgraf
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit

      - name: Kjør et bygg (avhengighetsgraf vil bli generert og sendt inn post-jobb)
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        run: ./gradlew --configuration-cache build -x :check -x :cyclonedxBom