name: Bygg og deploy app

# ------------------------------------------------------------
# Denne workflowen bygger en TypeScript-applikasjon, pusher docker-image til GAR og
# deployerer det hele til et valgfritt miljø.
#
# Forutsetninger: Repoet som kaller denne jobben må ha definert to scripts:
#  - yarn ci: Henter ned alle avhengigetene som prosjektet trenger
#  - yarn build: Bygger prod-versjon av appen
#
# Kallende GitHub Actions-jobb må sette følgende rettigheter:
#
# permissions:
#   id-token: write  # Trengs for deploy til GCP
#   packages: write  # Usikker på om denne egentlig kreves 🤔
# ------------------------------------------------------------

on:
  workflow_call:
    inputs:
      cluster:
        description: 'Cluster det skal deployes til'
        required: true
        type: string
      manifest:
        description: 'Sti til Nais-manifestet'
        required: true
        type: string
      node-version:
        description: 'Node-versjon'
        type: string
        required: false
        default: '20'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Bygg og last opp docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Sett opp Node ${{ inputs.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"

      - name: Installer avhengigheter
        run: yarn ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Bygg app
        run: yarn build

      - name: Last opp docker-image
        uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b # v0
        id: docker-push
        with:
          team: tilleggsstonader

  deploy:
    name: Deploy til ${{ inputs.cluster }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Deploy til ${{ inputs.cluster }}
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.manifest }}
          IMAGE: ${{ needs.build.outputs.image }}
