name: "Bygg app"

# ------------------------------------------------------------
# Denne workflowen bygger en TypeScript-applikasjon
#
# Forutsetninger: Repoet som kaller denne jobben må ha definert to scripts:
#  - yarn ci: Henter ned alle avhengigetene som prosjektet trenger
#  - yarn build: Bygger prod-versjon av appen
# ------------------------------------------------------------

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node-versjon'
        type: string
        required: false
        default: '20'

jobs:
  build:
    name: Bygg app
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Installer avhengigheter
        run: yarn ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Bygg app
        run: yarn build