apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-avslag-arsaker
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_avslag_arsaker
  description: "View som viser behandlinger med tilhørende fagsak"
  datasetRef:
    external: datastream_tilleggsstonader_sak
  view:
    useLegacySql: false
    query: >-
      SELECT
        v.behandling_id,
        JSON_VALUE(v.data, '$.type') AS type,
        arsak,
      FROM
        datastream_tilleggsstonader_sak.public_vedtak v,
        UNNEST(JSON_EXTRACT_ARRAY(v.data, '$.årsaker')) AS arsak
        WHERE type = 'AVSLAG';