apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-saksbehandling
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_saksbehandling
  description: "View som viser behandlinger med tilhørende fagsak"
  datasetRef:
    external: datastream_tilleggsstonader_sak
  view:
    useLegacySql: false
    query: >-
      SELECT 
        b.id as behandling_id,
        b.type,
        b.status,
        b.steg,
        b.resultat,
        b.arsak,
        b.henlagt_arsak,
        b.vedtakstidspunkt,
        b.revurder_fra,
        b.nye_opplysninger_kilde,
        fagsak.stonadstype as stonadstype,
        b.opprettet_tid,
        b.endret_tid
      FROM datastream_tilleggsstonader_sak.public_behandling b
      JOIN datastream_tilleggsstonader_sak.public_fagsak fagsak on b.fagsak_id = fagsak.id;