apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: saksbehandling
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge
spec:
  resourceID: saksbehandling
  description: "View som viser behandlinger med tilhørende fagsak"
  datasetRef:
    external: metabase_views
  view:
    useLegacySql: false
    query: >-
      SELECT b.type,
             b.status,
             b.steg,
             b.resultat,
             b.arsak,
             b.henlagt_arsak,
             b.vedtakstidspunkt,
             b.revurder_fra,
             b.opprettet_av,
             b.nye_opplysninger_kilde,
             fagsak.stonadstype as stonadstype,
             b.opprettet_tid,
             b.endret_tid
      FROM behandling b
               JOIN fagsak on b.fagsak_id = fagsak.id;