apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: view-sett-pa-vent-arsaker
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
    cnrm.cloud.google.com/project-id: {{project}}
spec:
  resourceID: view_sett_pa_vent_arsaker
  description: "View som viser én rad per årsak som saksbehandler oppgav da behandlingen ble satt på vent."
  datasetRef:
    external: datastream_tilleggsstonader_sak
  view:
    useLegacySql: false
    query: >-
      SELECT
          b.behandling_id,
          b.steg,
          b.endret_tid,
          JSON_VALUE(arsaker_json) as arsak,
      FROM `datastream_tilleggsstonader_sak.public_behandlingshistorikk` b,
           UNNEST(JSON_EXTRACT_ARRAY(b.metadata, '$.årsaker')) as arsaker_json